
from typing import Protocol,runtime_checkable

@runtime_checkable
class StorageBackend(Protocol):
    """存储层统一接口（CRUD）"""
    # C
    def create_session(self, session_id: str, name: str) -> None: ...
    # R
    def get_session_by_id(self, session_id: str) -> dict | None: ...
    def get_session_by_name(self, name: str) -> dict | None: ...
    def list_sessions(self) -> list[dict]: ...
    def get_messages(self, session_id: str) -> list[dict]: ...
    # U
    def append_messages(self, session_id: str, messages: list[dict]) -> None: ...
    def rename_session(self, session_id: str, new_name: str) -> None: ...
    # D
    def delete_session(self, session_id: str) -> None: ...